name: Python CI for GradCheck

on:
  push:
  pull_request:

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run check_graduation script
      run: python check_graduation.py
